version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Contraseña del usuario root
      MYSQL_DATABASE: telegram-bot          # Base de datos a crear
      MYSQL_USER: myuser                  # Usuario adicional
      MYSQL_PASSWORD: mypassword           # Contraseña del usuario adicional
    ports:
      - "3306:3306"                        # Exponer el puerto de MySQL
    volumes:
      - db_data:/var/lib/mysql             # Persistencia de datos
  
  app:
    build:
      context: .                           # Contexto donde está el Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306                  # Puerto para MySQL
      DATABASE_NAME: telegram-bot
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always                    # Cambia el puerto según lo necesites

volumes:
  db_data:

